"""Shared project-name normalization helpers."""

from __future__ import annotations

import json
import os
import re
import sqlite3
from pathlib import Path
from typing import Dict, Optional

_PROJECT_ALIASES = {
    "office-automation": "office-automate",
    "claude-automate": "office-automate",
    "financial-analysis": "fractal",
    "market generator": "fractal",
    "fms-branch": "fractal",
    "claude-session-manager": "session-manager",
}

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKTREE_MAP_PATH = REPO_ROOT / "data" / "worktree_map.json"
GITHUB_PRS_DB_PATH = REPO_ROOT / "data" / "office_climate.db"
_TICKET_PREFIX_RE = re.compile(r"^(\d{4})-")

# Directories that may contain git repos (scanned for worktree reverse lookup)
_REPO_SEARCH_DIRS = [
    Path.home() / "Desktop",
    Path.home() / "Desktop" / "automation",
]

# Cache: worktree name -> parent repo basename
_worktree_map: Dict[str, str] = {}
_worktree_map_loaded = False


def _repo_basename_from_gitdir(gitdir: str) -> Optional[str]:
    """Extract repo basename from a gitdir path like .../repo/.git/worktrees/name."""
    parts = gitdir.replace("\\", "/").split("/")
    try:
        idx = parts.index(".git")
        repo_root = "/".join(parts[:idx])
        return os.path.basename(repo_root) or None
    except ValueError:
        return None


def _resolve_worktree_from_disk(path: str) -> Optional[str]:
    """Read the .git file in an active worktree to find its parent repo."""
    git_file = os.path.join(path, ".git")
    try:
        if os.path.isfile(git_file):
            with open(git_file) as f:
                line = f.readline().strip()
            if line.startswith("gitdir:"):
                gitdir = line.split(":", 1)[1].strip()
                return _repo_basename_from_gitdir(gitdir)
    except OSError:
        pass
    return None


def _load_worktree_map() -> Dict[str, str]:
    """Load the worktree mapping file (generated by build_worktree_map)."""
    global _worktree_map, _worktree_map_loaded
    if _worktree_map_loaded:
        return _worktree_map
    _worktree_map_loaded = True
    try:
        if WORKTREE_MAP_PATH.is_file():
            with open(WORKTREE_MAP_PATH) as f:
                _worktree_map = json.load(f)
    except (OSError, json.JSONDecodeError):
        pass
    return _worktree_map


def build_worktree_map() -> Dict[str, str]:
    """Scan repos and active worktrees to build name -> repo basename map.

    Call this on the work Mac (which has the repos and worktrees on disk)
    and write the result to data/worktree_map.json.

    Cumulative: seeds from any existing worktree_map.json so resolutions
    persist after worktrees and their branches are pruned.
    """
    mapping: Dict[str, str] = {}

    # 0. Seed from existing map so previously resolved names survive pruning
    try:
        if WORKTREE_MAP_PATH.is_file():
            with open(WORKTREE_MAP_PATH) as f:
                existing = json.load(f)
            if isinstance(existing, dict):
                mapping.update({k: v for k, v in existing.items() if isinstance(v, str)})
    except (OSError, json.JSONDecodeError):
        pass

    # 1. Scan known repo dirs for .git/worktrees/ metadata
    for search_dir in _REPO_SEARCH_DIRS:
        if not search_dir.is_dir():
            continue
        for entry in search_dir.iterdir():
            wt_dir = entry / ".git" / "worktrees"
            if wt_dir.is_dir():
                repo_name = entry.name
                for wt in wt_dir.iterdir():
                    if wt.is_dir():
                        mapping[wt.name] = repo_name

    # 2. Scan active worktree directories (~/worktrees/)
    wt_root = Path.home() / "worktrees"
    if wt_root.is_dir():
        for wt in wt_root.iterdir():
            if wt.name in mapping:
                continue
            parent = _resolve_worktree_from_disk(str(wt))
            if parent:
                mapping[wt.name] = parent

    # 3. Match unresolved worktree names against branch names in known repos
    #    (catches pruned worktrees whose branches still exist)
    history_path = Path.home() / ".claude" / "history.jsonl"
    unresolved_names: set[str] = set()
    if history_path.is_file():
        try:
            with open(history_path) as f:
                for line in f:
                    try:
                        record = json.loads(line)
                        proj = record.get("project", "")
                        if proj and "/worktrees/" in proj:
                            wt_name = os.path.basename(proj.rstrip("/"))
                            if wt_name not in mapping:
                                unresolved_names.add(wt_name)
                    except (json.JSONDecodeError, KeyError):
                        pass
        except OSError:
            pass

    if unresolved_names:
        import subprocess

        for search_dir in _REPO_SEARCH_DIRS:
            if not search_dir.is_dir() or not unresolved_names:
                continue
            for entry in search_dir.iterdir():
                if not (entry / ".git").exists():
                    continue
                try:
                    result = subprocess.run(
                        ["git", "-C", str(entry), "branch", "--list", "--no-color"],
                        capture_output=True, text=True, timeout=5,
                    )
                    branches = {b.strip().lstrip("* ") for b in result.stdout.splitlines()}
                    matched = unresolved_names & branches
                    for name in matched:
                        mapping[name] = entry.name
                    unresolved_names -= matched
                except (subprocess.SubprocessError, OSError):
                    pass

    # 4. Ticket-prefix fallback: for unresolved 4-digit-prefixed names,
    #    look up '#NNNN' in github_prs.title and pick the dominant repo.
    if unresolved_names and GITHUB_PRS_DB_PATH.is_file():
        candidates = {
            name: m.group(1)
            for name in unresolved_names
            if (m := _TICKET_PREFIX_RE.match(name))
        }
        if candidates:
            try:
                with sqlite3.connect(str(GITHUB_PRS_DB_PATH)) as conn:
                    for name, ticket in candidates.items():
                        rows = conn.execute(
                            "SELECT repo, COUNT(*) AS n FROM github_prs "
                            "WHERE title LIKE ? GROUP BY repo ORDER BY n DESC, repo",
                            (f"%#{ticket}%",),
                        ).fetchall()
                        if rows:
                            mapping[name] = rows[0][0]
                            unresolved_names.discard(name)
            except sqlite3.Error:
                pass

    return mapping


def _resolve_worktree_parent(path: str) -> Optional[str]:
    """Resolve a worktree path to its parent repo basename."""
    # 1. Active worktree on disk: read .git file
    result = _resolve_worktree_from_disk(path)
    if result:
        return result

    # 2. Worktree map file (works on Mac Mini without filesystem access)
    wt_name = os.path.basename(path.rstrip("/"))
    wt_map = _load_worktree_map()
    return wt_map.get(wt_name)


def normalize_project_name(project_name: Optional[str]) -> str:
    """Return a canonical project identifier for paths and repo basenames."""
    if not project_name:
        return "unknown"

    # Normalize backslashes so basename / substring checks work uniformly
    # for Windows-style worktree paths on POSIX runtimes.
    normalized = project_name.strip().replace("\\", "/").rstrip("/")
    if not normalized:
        return "unknown"

    # Resolve git worktrees to their parent repo
    if "/worktrees/" in normalized:
        parent = _resolve_worktree_parent(normalized)
        if parent:
            normalized = parent

    basename = os.path.basename(normalized) or normalized

    # Bare basename may itself be a worktree name (path was already stripped
    # upstream, e.g. when reading from orchestration_activity).
    wt_map = _load_worktree_map()
    if basename in wt_map:
        basename = wt_map[basename]

    basename_lower = basename.lower()

    if basename_lower == "fractal" or basename_lower.startswith("fractal-"):
        return "fractal"

    return _PROJECT_ALIASES.get(basename_lower, basename)
